<?php
/**
 *@var Post[] $posts
 */
$this->title = 'Об авторе';
?>
<h1><?php echo $this->title;?></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent a lorem eu turpis auctor auctor. Cras est mauris, vulputate nec lectus ac, vulputate hendrerit est. Sed ut sapien vitae sapien volutpat tristique in et massa. Mauris eget fermentum leo. Sed purus mi, malesuada eget vehicula sed, consectetur eget risus. Nam mi dolor, auctor non felis sed, volutpat dignissim diam. Cras nec iaculis ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean ac urna molestie, elementum eros id, ornare arcu. In hac habitasse platea dictumst.</p>

<p>Nunc vitae neque id ipsum sodales fermentum. Proin ut semper quam, eu sodales turpis. Pellentesque porttitor nec lectus eget cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur vel mollis tortor, quis molestie diam. Nam consequat augue ac orci condimentum tempor. Ut elementum tempor purus, eu porta lacus convallis ut. Sed condimentum aliquet massa, et tempus nibh iaculis ac. In nec congue libero, nec egestas diam. Mauris dignissim non ex at tempus. Morbi at finibus lectus, dignissim semper risus. Duis ligula tellus, finibus quis eros sit amet, aliquam interdum diam. Suspendisse ut nulla mi. Nullam id augue turpis. Nunc in est sapien. Integer euismod lectus neque, quis semper dui varius non.</p>

<p>Vestibulum commodo, quam et hendrerit pellentesque, augue sapien euismod lorem, vitae ultrices ligula orci a nibh. Integer molestie, dolor consequat iaculis imperdiet, mi dui ultricies justo, et gravida nibh tortor a justo. Integer ullamcorper ut odio eu eleifend. Sed dapibus eu nisi et gravida. Quisque sit amet enim vel dolor viverra pharetra ut maximus ante. Suspendisse orci libero, gravida nec iaculis vulputate, tincidunt a tortor. Maecenas imperdiet dolor lacus, et sodales massa vehicula ac. In nec sapien quis turpis mollis ullamcorper. Curabitur euismod, tellus ut porttitor auctor, risus ex condimentum felis, eget lacinia risus erat at elit. Curabitur in consectetur ipsum, semper congue nunc. Donec fringilla leo metus, ac malesuada ante tempus ac. Donec et fringilla ante. Sed tellus mi, aliquam at massa sed, eleifend efficitur diam.</p>